### ISSUE TITLE
Build error with ndk 12b on Ubuntu 64 bit when building arm-linux-androideabi

### ISSUE THREAD

**Issue by andreas-repp** [buffer51/android-gfortran#3]
I followed the steps you described in the README.md. However, when I run `./build.py --toolchain arm-linux-androideabi` I end up with the following error:

```
                            ^
mv -f .deps/Generator_System.Tpo .deps/Generator_System.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src -I..  -I.. -I/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src  -I/tmp/ndk-andreas/build/toolchain/temp-install/include  -g -O2 -frounding-math -O2 -s  -I/tmp/ndk-andreas/build/toolchain/temp-install/include -W -Wall -MT Matrix.lo -MD -MP -MF .deps/Matrix.Tpo -c -o Matrix.lo /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Matrix.cc
mv -f .deps/Grid_Generator_System.Tpo .deps/Grid_Generator_System.Plo
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src -I..  -I.. -I/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src  -I/tmp/ndk-andreas/build/toolchain/temp-install/include  -g -O2 -frounding-math -O2 -s  -I/tmp/ndk-andreas/build/toolchain/temp-install/include -W -Wall -MT Scalar_Products.lo -MD -MP -MF .deps/Scalar_Products.Tpo -c -o Scalar_Products.lo /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc
Makefile:1159: recipe for target 'Grid_Generator.lo' failed
make[4]: *** [Grid_Generator.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src -I.. -I.. -I/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src -I/tmp/ndk-andreas/build/toolchain/temp-install/include -g -O2 -frounding-math -O2 -s -I/tmp/ndk-andreas/build/toolchain/temp-install/include -W -Wall -MT Matrix.lo -MD -MP -MF .deps/Matrix.Tpo -c /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Matrix.cc -o Matrix.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src -I.. -I.. -I/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src -I/tmp/ndk-andreas/build/toolchain/temp-install/include -g -O2 -frounding-math -O2 -s -I/tmp/ndk-andreas/build/toolchain/temp-install/include -W -Wall -MT Scalar_Products.lo -MD -MP -MF .deps/Scalar_Products.Tpo -c /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc -o Scalar_Products.o
mv -f .deps/Coefficient.Tpo .deps/Coefficient.Plo
mv -f .deps/Generator.Tpo .deps/Generator.Plo
In file included from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Constraint.defs.hh:32:0,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.inlines.hh:29,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.defs.hh:196,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc:26:
/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Constraint_System.defs.hh:207:7: error: 'ptrdiff_t' was not declared in this scope
       ptrdiff_t,
       ^
/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Constraint_System.defs.hh:207:7: note: suggested alternatives:
In file included from /usr/include/c++/4.9/iostream:38:0,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/checked.defs.hh:27,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Checked_Number.defs.hh:28,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Coefficient.types.hh:16,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.defs.hh:29,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc:26:
/usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:189:28: note:   'std::ptrdiff_t'
   typedef __PTRDIFF_TYPE__ ptrdiff_t;
                            ^
/usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:189:28: note:   'std::ptrdiff_t'
In file included from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Constraint.defs.hh:32:0,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.inlines.hh:29,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.defs.hh:196,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc:26:
/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Constraint_System.defs.hh:209:24: error: template argument 3 is invalid
       const Constraint&> {
                        ^
In file included from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Generator.defs.hh:32:0,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.inlines.hh:30,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.defs.hh:196,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc:26:
/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Generator_System.defs.hh:253:7: error: 'ptrdiff_t' was not declared in this scope
       ptrdiff_t,
       ^
/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Generator_System.defs.hh:253:7: note: suggested alternatives:
In file included from /usr/include/c++/4.9/iostream:38:0,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/checked.defs.hh:27,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Checked_Number.defs.hh:28,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Coefficient.types.hh:16,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.defs.hh:29,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc:26:
/usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:189:28: note:   'std::ptrdiff_t'
   typedef __PTRDIFF_TYPE__ ptrdiff_t;
                            ^
/usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:189:28: note:   'std::ptrdiff_t'
In file included from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Generator.defs.hh:32:0,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.inlines.hh:30,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.defs.hh:196,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc:26:
/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Generator_System.defs.hh:255:23: error: template argument 3 is invalid
       const Generator&> {
                       ^
In file included from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Congruence.defs.hh:36:0,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.inlines.hh:31,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.defs.hh:196,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc:26:
/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Congruence_System.defs.hh:238:7: error: 'ptrdiff_t' was not declared in this scope
       ptrdiff_t,
       ^
/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Congruence_System.defs.hh:238:7: note: suggested alternatives:
In file included from /usr/include/c++/4.9/iostream:38:0,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/checked.defs.hh:27,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Checked_Number.defs.hh:28,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Coefficient.types.hh:16,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.defs.hh:29,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc:26:
/usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:189:28: note:   'std::ptrdiff_t'
   typedef __PTRDIFF_TYPE__ ptrdiff_t;
                            ^
/usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:189:28: note:   'std::ptrdiff_t'
In file included from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Congruence.defs.hh:36:0,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.inlines.hh:31,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.defs.hh:196,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc:26:
/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Congruence_System.defs.hh:240:24: error: template argument 3 is invalid
       const Congruence&> {
                        ^
In file included from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Grid_Generator.defs.hh:29:0,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.inlines.hh:32,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.defs.hh:196,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc:26:
/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Grid_Generator_System.defs.hh:270:7: error: 'ptrdiff_t' was not declared in this scope
       ptrdiff_t,
       ^
/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Grid_Generator_System.defs.hh:270:7: note: suggested alternatives:
In file included from /usr/include/c++/4.9/iostream:38:0,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/checked.defs.hh:27,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Checked_Number.defs.hh:28,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Coefficient.types.hh:16,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.defs.hh:29,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc:26:
/usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:189:28: note:   'std::ptrdiff_t'
   typedef __PTRDIFF_TYPE__ ptrdiff_t;
                            ^
/usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:189:28: note:   'std::ptrdiff_t'
In file included from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Grid_Generator.defs.hh:29:0,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.inlines.hh:32,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.defs.hh:196,
                 from /tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Scalar_Products.cc:26:
/tmp/ndk-andreas/build/toolchain/temp-src/ppl-0.11.2/src/Grid_Generator_System.defs.hh:272:28: error: template argument 3 is invalid
       const Grid_Generator&>,
                            ^
mv -f .deps/Init.Tpo .deps/Init.Plo
Makefile:1159: recipe for target 'Scalar_Products.lo' failed
make[4]: *** [Scalar_Products.lo] Error 1
mv -f .deps/Linear_Expression.Tpo .deps/Linear_Expression.Plo
mv -f .deps/Matrix.Tpo .deps/Matrix.Plo
mv -f .deps/Linear_System.Tpo .deps/Linear_System.Plo
make[4]: Leaving directory '/tmp/ndk-andreas/build/toolchain/ppl-0.11.2/src'
Makefile:951: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/tmp/ndk-andreas/build/toolchain/ppl-0.11.2/src'
Makefile:478: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/ndk-andreas/build/toolchain/ppl-0.11.2'
Makefile:405: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/tmp/ndk-andreas/build/toolchain/ppl-0.11.2'
Makefile:670: recipe for target 'stmp-build-host-ppl' failed
make: *** [stmp-build-host-ppl] Error 2
Error while building toolchain. See /tmp/ndk-andreas/build/toolchain/config.log
Traceback (most recent call last):
  File "./build.py", line 64, in <module>
    build_support.run(main, ArgParser)
  File "/home/andreas/programs/ndk/build/lib/build_support.py", line 313, in run
    main_func(args)
  File "./build.py", line 61, in main
    build_support.build(build_cmd, args)
  File "/home/andreas/programs/ndk/build/lib/build_support.py", line 174, in build
    subprocess.check_call(cmd + common_args, env=build_env)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bash', 'build-gcc.sh', '/home/andreas/programs/toolchain', '/home/andreas/programs/ndk', 'arm-linux-androideabi-4.9', '-j8', '--sysroot=/home/andreas/programs/ndk/platforms/android-9/arch-arm', '--try-64', '--verbose', '--package-dir=/home/andreas/programs/out/dist']' returned non-zero exit status 1
```

Am I missing something? Or is there something different with the newer version of the ndk?

Many thanks in advance!

**Comment by buffer51** [comment]
Hi @andreas-eberle,

I tried it myself today, and experienced the same problem. In fact even trying to build the toolchain for r12b without any changes fails. As far as I can tell, something in the NDK sources that used to include/define ptrdiff_t was removed.

I find it hard to believe that no one even tried to build the toolchain before releasing the NDK, but am confused as to what we are doing wrong. I created an issue on their Github repository (android-ndk/ndk#187), we'll see what they can tell us.

**Comment by buffer51** [comment]
@andreas-eberle You'll be happy to know that I was able to fix the problem. Instead of using the manual setup I had layed out in instructions, I changed it to follow the official procedure for building the toolchain.

For some reason using the NDK sources from `prebuilt/` doesn't cause the same problem using the packaged NDK does.

**Comment by andreas-repp** [comment]
Many thanks for your efforts!
